### ISSUE TITLE
many2many write does not works

### ISSUE THREAD

**Issue by Yevsyukov** [muk-it/muk_docs#1]
I trying to update many2many field in product.template.public_categ_ids but does not see the changes

**Comment by keshrath** [comment]
Hello, can you give me a bit more information? What are you trying to achieve? How does your request look like?

**Comment by Yevsyukov** [comment]
Hi,
my url is: https://***/api/write?token=*****&model=product.template&values={"ref" : "A3VU150", "name" : "32","website_published":"true","type":"product","default_code":"A3VU150","description_sale":"22","list_price":"76.67","public_categ_ids":[8,9]}&ids=[3334]

method: PUT

Problem with "public_categ_ids". It is many2many and I can't to update or insert new relations.

Thanks!

**Comment by keshrath** [comment]
Hello, I had no time yet to try it out myself, but I noticed that you set the public_categ_ids as an array of IDs? right? Odoo does this a bit differently.

```
(0, 0,  { values })    link to a new record that needs to be created with the given values dictionary
(1, ID, { values })    update the linked record with id = ID (write *values* on it)
(2, ID)                remove and delete the linked record with id = ID (calls unlink on ID, that will delete the object completely, and the link to it as well)
(3, ID)                cut the link to the linked record with id = ID (delete the relationship between the two objects but does not delete the target object itself)
(4, ID)                link to existing record with id = ID (adds a relationship)
(5)                    unlink all (like using (3,ID) for all linked records)
(6, 0, [IDs])          replace the list of linked IDs (like using (5) then (4,ID) for each ID in the list of IDs)

Example:
[(6, 0, [8, 5, 6, 4])] sets the many2many to ids [8, 5, 6, 4]
```
If this doesn't solve your problem please let me know :)

**Comment by Yevsyukov** [comment]
Unfortunately, I've error 400 in this case.

**Comment by keshrath** [comment]
I ran it through our test system and it seems to be working. A 400 error is usually thrown if it cannot properly parse the json passed by the request. What exactly does your query look like now?

`https:///api/write?token=**&model=product.template&values={"ref" : "A3VU150", "name" : "32","website_published":"true","type":"product","default_code":"A3VU150","description_sale":"22","list_price":"76.67","public_categ_ids":[[6,0,[8,9]]]}&ids=[3334]`

**Comment by Yevsyukov** [comment]
Yes, exactly the same url :(
Manually I can assign these values. Should works, but...

**Comment by Yevsyukov** [comment]
Hi,
yes, you are right. This value "... "public_categ_ids":[(6,0,[8,9])] ...." is a cause of json invalidation. Odoo return a message - No JSON object could be decoded

**Comment by keshrath** [comment]
Hi, ok I tested it with the many2many field in res.partner:

`https://muk-rest-demo.mukit.at/api/write?token=a_rYSE...&ids=[9]&values={"category_id": [[6, 0, [1,2]]]}`

Depending on your implementation you might have to decode the URL as well and use 
square brackets instead of round brackets.

`https://muk-rest-demo.mukit.at/api/write?token=a_rYSE...&ids=%5B9%5D&values=%7B%22category_id%22%3A+%5B%5B6%2C+0%2C+%5B1%2C2%5D%5D%5D%7D`

Query:

![image](https://user-images.githubusercontent.com/4851083/38131764-8d592faa-3408-11e8-999b-b4b6c32a4731.png)

Decode:

![image](https://user-images.githubusercontent.com/4851083/38131780-9eadecdc-3408-11e8-84dc-9df235d5eafa.png)

Result:

![image](https://user-images.githubusercontent.com/4851083/38131802-af127dd6-3408-11e8-9dfe-6451e6d1213c.png)

Tool: [Advanced REST client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo)

**Comment by Yevsyukov** [comment]
Thank you very match! 
The problem was in brackets!
